name: ArmorStandExpanded
main: HighTec\ArmorStandExpanded\ArmorStandExpanded
version: 1.0
api:
- 3.4.0
mcpe-protocol: 408
author: HighTec
description: "Adds fully functional ArmorStands to your Pocketmine-MP Server. Supports the MyPlot Plot-Protection"
load: STARTUP
